/******************************************************************************************************
Class Name         : ApplicationException
Description        : This class is used for creating custom Exception object with custom messages.
Created By         : Himanshu Raichandani
Created On         : 15-June-2015 
******************************************************************************************************/
public class ApplicationException extends Exception{}