/******************************************************************************************************
Class Name         : ScheduleDeleteCommunications
Description        : A scheduler for scheduled delete for communications
Created By         : Rahul Agarwal 
Created On         : 07/16/2015
******************************************************************************************************/
global class ScheduleDeleteCommunications implements Schedulable{
    /**
    * Method name  : execute
    * Description  : This method executes the call for batch operation
    * Return Type  : void
    * Parameter    : SchedulableContext
    **/
    global void execute(SchedulableContext SC){
        /*BatchDeleteCommuications cVar = new BatchDeleteCommuications();
        database.executebatch(cVar);*/
    }
}