NAME,FIELD_NAME__C,HEIGHT__C,NO_OF_MONTHS_FOR_CONDITION_1__C,NO_OF_MONTHS_FOR_CONDITION_2__C,VALUE1_FOR_AGE__C,VALUE2_FOR_AGE__C,VALUE_1__C,VALUE_2__C,VALUE_3__C,VALUE_4__C,VALUE_5__C,VALUE_FOR_HEIGHT__C
WFH,Weight_Kg__c,120,60,,Age Greater Than 5 Years,,Severely Wasted,Moderately Wasted,OK,,,Height Greater Than 120 Cm
BMI,BMI__c,,228,61,Age Greater Than 228 Months,Age Less Than 61 Months,Severely Thin,Moderately Thin,Obese,Overweight,OK,
WFA,Weight_Kg__c,,120,,Age Greater Than 10 Years,,Severely Underweight,Moderately Underweight,OK,Age Greater Than 10 Years,,
HFA,Height_Cm__c,,228,,Age Greater Than 19 Years,,Severely Stunted,Moderately Stunted,OK,Age Greater Than 19 Years,,
